/**
 * The one place code gets the logo and icons from. The files are generated by
 * `npm run brand` (scripts/brand/build.mjs), which also writes brand-logo.json:
 * the logo's size, so every <img> reserves the right space, and a version that
 * changes with the artwork, so browsers fetch new files instead of a cached copy.
 */

import generated from "./brand-logo.json";

const v = `?v=${generated.version}`;

export const BRAND_LOGO = {
  /** For light backgrounds. */
  light: `/brand/merasoftware-logo.svg${v}`,
  /** For navy/dark backgrounds. */
  dark: `/brand/merasoftware-logo-dark.svg${v}`,
  width: generated.width,
  height: generated.height,
  alt: "Mera Software — Digital Solutions",
};

export const BRAND_ICONS = {
  icon192: `/icons/icon-192.png${v}`,
  icon512: `/icons/icon-512.png${v}`,
  appleTouch: `/icons/apple-touch-icon.png${v}`,
};
