import Link from "@/components/link"; import { notFound } from "next/navigation"; import { SiteFooter } from "@/components/site-footer"; import { SiteHeader } from "@/components/site-header"; import { services } from "@/lib/site-data";
import { pageMetadata } from "@/lib/page-seo";
import { loadVisuals } from "@/lib/section-visuals";
import { SectionVisual } from "@/components/section-visual";
import type { VisualSlotId } from "@/lib/visual-slots";
// Search details are editable at /admin/page-seo, so they are read per request.
export const dynamic = "force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;return services.some(s=>s.slug===slug)?pageMetadata(`service-${slug}`):{title:"Service"};}
export default async function ServiceDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=services.find(s=>s.slug===slug);if(!service)notFound();const visualKey=slug==="website-development"?"service.website":slug==="seo"?"service.seo":"service.marketing";const heroSlot=`${visualKey}.hero` as VisualSlotId;const includedSlot=`${visualKey}.included` as VisualSlotId;const visuals=await loadVisuals([heroSlot,includedSlot]);return <><SiteHeader/><main><section className="page-hero"><div className="container visual-page-hero"><div><p className="eyebrow"><i/> {service.eyebrow}</p><h1>{service.title}</h1><p>{service.description}</p></div><SectionVisual data={visuals[heroSlot]} label={`${service.title} illustration`} /></div></section><section className="content-section container"><div className="section-top"><p className="eyebrow"><i/> WHAT&apos;S INCLUDED</p><p className="side-note">A focused engagement, tailored to your current priorities.</p></div><div className="visual-feature"><div><div className="service-list" style={{marginTop:48}}>{service.points.map((point,index)=><div className="service" key={point}><span className="service-number">0{index+1}</span><h3>{point}</h3><span className="service-arrow">+</span></div>)}</div><div style={{marginTop:56}}><Link className="button button-dark" href="/contact">Talk about this service <span>→</span></Link></div></div><SectionVisual data={visuals[includedSlot]} label="Services included illustration" /></div></section></main><SiteFooter/></>}
