"use client";
import { useState } from "react";
import { packages, categories, money, type Category } from "@/lib/campaign-packages";
import { PackageCard } from "./package-card";
import s from "./campaign.module.css";
export function StaffPackages() {
  const [category, setCategory] = useState<Category>("social");
  const selected = packages.filter(p => p.category === category);
  return <div className={s.staff}><section className={s.showcaseHero}><p className={s.kicker}>DIGITAL MARKETING & WEBSITE PACKAGES</p><h1>Every business has a next step.<br/><em>Find the right package.</em></h1><p>One-time setup, ongoing promotion or a complete business website. Compare the scope and pricing in one place.</p><div className={s.pills}><span>12 packages</span><span>4 service categories</span><span>Clear monthly & website pricing</span></div><div className={s.actions}><a className={s.button} href="/campaign/business-growth" target="_blank" rel="noreferrer">Try the client interaction page ↗</a></div></section><div className={s.tabs}>{Object.entries(categories).map(([id, label]) => <button key={id} aria-pressed={category === id} onClick={() => setCategory(id as Category)}>{label}</button>)}</div><h2>{categories[category]}</h2><p className={s.fine}>Compare packages below. Open quotation notes when preparing a client proposal.</p><div className={s.tableWrap}><table className={s.table}><caption>Compare {categories[category]}</caption><thead><tr><th>Package</th><th>Price</th><th>Reels</th><th>Photos</th><th>Shoots</th><th>Website</th><th>Ad budget</th></tr></thead><tbody>{selected.map(p => <tr key={p.id}><td>{p.name}</td><td>{money(p.price)} {p.cadence}</td><td>{p.reels ?? "—"}</td><td>{p.photos ?? "—"}</td><td>{p.shoots ?? "—"}</td><td>{p.website ?? "—"}</td><td>{["premium", "complete", "pro"].includes(p.id) ? "Up to ₹2,000" : "Not listed"}</td></tr>)}</tbody></table></div><div className={s.grid}>{selected.map(p => <PackageCard plan={p} staff key={p.id}/>)}</div><section className={s.section}><h2>Call & quotation guide</h2><div className={s.card}><ul className={s.list}><li>Setup is one-time. Social and combined plans are monthly. Website-only payment terms need confirmation.</li><li>Basic, Growth and Growth Plus: 4 / 6 / 8 reels respectively. Each includes 4 photo posts and requires client-provided raw content.</li><li>Professional: 1 shoot and 8 photo posts. Professional Plus: 2 shoots plus Q&A / polls. Premium: up to 4 shoots and up to ₹2,000 ad budget.</li><li>Business Complete includes a static website; Business Pro includes a dynamic website. Confirm dynamic functionality before recommending.</li><li>Confirm domain, hosting, taxes, shoot travel, SEO scope, updates, delivery, combined-plan commitment and website ownership before quoting.</li></ul></div></section></div>;
}
