/* eslint @next/next/no-img-element: off -- static brand and owner-provided work images. */
"use client";
import { useEffect, useState } from "react";
import { BRAND_LOGO } from "@/lib/brand";
import { campaignTrust as content } from "@/lib/campaign-trust";
import { money, packages } from "@/lib/campaign-packages";
import s from "./trust-campaign.module.css";

function Icon({ type }: { type: "arrow" | "check" | "phone" | "message" }) {
  const paths = { arrow: "M5 12h14m-6-6 6 6-6 6", check: "m5 12 4 4 10-10", phone: "M7 3H4a1 1 0 0 0-1 1c0 9 8 17 17 17a1 1 0 0 0 1-1v-3l-5-2-2 2a15 15 0 0 1-7-7l2-2-2-5Z", message: "M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-1 1v-9.5A8.5 8.5 0 0 1 11.5 3h1a8.5 8.5 0 0 1 8.5 8.5ZM7 11h10m-10 4h6" };
  return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[type]}/></svg>;
}
const email = "contact@merasoftware.com";
function contactHref(offer = false) {
  const text = offer ? `Namaste, mujhe ${content.offer?.title} ke demo aur offer ke baare mein baat karni hai. Please eligibility aur price confirm karein.` : "Namaste, mujhe apne business ki website / online promotion ke liye aapse baat karni hai. Please suitable service aur cost samjhayein.";
  return content.whatsapp ? `https://wa.me/${content.whatsapp.replace(/\D/g, "")}?text=${encodeURIComponent(text)}` : `mailto:${email}?subject=${encodeURIComponent(offer ? "Starter offer & demo enquiry" : "Business website & promotion enquiry")}&body=${encodeURIComponent(text)}`;
}
function ContactButtons({ offer = false }: { offer?: boolean }) {
  return <div className={s.actions}><a className={s.primary} href={contactHref(offer)}><Icon type="message"/>{content.whatsapp ? "WhatsApp par baat karein" : "Message karein"}<Icon type="arrow"/></a>{content.phone && <a className={s.secondary} href={`tel:${content.phone.replace(/[^+\d]/g, "")}`}><Icon type="phone"/>Call karein</a>}</div>;
}
function Countdown({ end }: { end: string }) {
  const [remaining, setRemaining] = useState<number | null>(null);
  useEffect(() => { const tick = () => setRemaining(Math.max(0, Date.parse(end) - Date.now())); tick(); const timer = setInterval(tick, 1000); return () => clearInterval(timer); }, [end]);
  if (!Number.isFinite(Date.parse(end))) return <p>Current offer details ke liye contact karein.</p>;
  if (remaining === null) return <p>Offer deadline: {new Date(end).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST</p>;
  if (!remaining) return <p>Offer end ho chuka hai. Current pricing ke liye contact karein.</p>;
  const total = Math.floor(remaining / 1000);
  return <div className={s.timer} aria-label="Offer time remaining">{[[Math.floor(total / 86400), "Days"], [Math.floor(total / 3600) % 24, "Hours"], [Math.floor(total / 60) % 60, "Minutes"], [total % 60, "Seconds"]].map(([value, label]) => <div key={label}><b>{String(value).padStart(2, "0")}</b><span>{label}</span></div>)}</div>;
}
export function TrustCampaign() {
  const [now, setNow] = useState<number | null>(null);
  useEffect(() => { const tick = () => setNow(Date.now()); tick(); const timer = setInterval(tick, 1000); return () => clearInterval(timer); }, []);
  const offer = content.offer;
  const active = !!offer && now !== null && Number.isFinite(Date.parse(offer.endsAt)) && now < Date.parse(offer.endsAt);
  const price = (id: string) => packages.find(p => p.id === id)!.price;
  return <main className={s.page}>
    <header className={s.header}><div className={s.headerInner}><img src={BRAND_LOGO.light} width={BRAND_LOGO.width} height={BRAND_LOGO.height} alt={BRAND_LOGO.alt}/><a href="#contact">Let&apos;s talk <Icon type="arrow"/></a></div></header>
    <section className={`${s.container} ${s.hero}`}><div className={s.heroCopy}><span className={s.eyebrow}><i/>WEBSITES · SOCIAL MEDIA · BUSINESS PROMOTION</span><h1>Aap business sambhaliye.<br/><em>Online presence<br/>hum sambhalenge.</em></h1><p>Website banwani ho ya Google, Instagram aur Facebook par business promote karna ho — pehle aapki zarurat samjhenge, phir sahi service aur kharch batayenge.</p><ContactButtons/><p className={s.micro}>Pehle baat karein. Package aur kaam ka scope samajhkar decide karein.</p><div className={s.heroPoints}><span><Icon type="check"/>Clear starting prices</span><span><Icon type="check"/>Aapki requirement ke hisaab se plan</span></div></div>
      <div className={s.visual} aria-label="Illustrative website and social content design previews"><span className={s.visualLabel}>A BUSINESS THAT LOOKS READY.</span><div className={s.browser}><div className={s.browserTop}><span/><span/><span/><small>Your business, online.</small></div><div className={s.sampleNav}><b>YOUR BUSINESS</b><span>Services · About · Contact</span></div><div className={s.sampleHero}><span>MADE FOR YOUR NEXT CUSTOMER</span><h2>Good business.<br/>Great first impression.</h2><p>Your services. Your story. One clear place.</p><div>Explore our services →</div><div className={s.sampleShape} aria-hidden="true"/></div><div className={s.sampleTiles}><span>Our services</span><span>Our work</span><span>Get in touch</span></div></div><div className={s.socialPreview}><div className={s.socialProfile}><b>B</b><div><strong>Your business</strong><small>Social content preview</small></div><span>•••</span></div><div className={s.socialArt}><span>SHOW UP.<br/>STAND OUT.</span><small>CONTENT THAT REPRESENTS YOUR BUSINESS</small></div><p>♡ &nbsp; ◯ &nbsp; ↗ <span>▱</span></p></div><div className={s.visualChip}><Icon type="check"/>Website + social presence</div><p className={s.previewNote}>Illustrative design previews · client projects ya results nahi.</p></div>
    </section>
    <div className={s.serviceStrip}><div className={s.container}><span>Website development</span><i>✦</i><span>Social media management</span><i>✦</i><span>Google Business Profile</span><i>✦</i><span>Content shoots</span></div></div>
    {content.stats.length > 0 && <section className={`${s.container} ${s.stats}`} aria-label="Our verified experience">{content.stats.map(stat => <div key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</section>}
    {content.work.length > 0 && <section className={`${s.container} ${s.section}`}><span className={s.eyebrow}>OUR WORK</span><h2>Sirf kehna nahi.<br/>Kaam bhi dekhiye.</h2><div className={s.workGrid}>{content.work.map(w => <a href={w.url} key={w.title} className={s.workCard} target="_blank" rel="noreferrer"><img src={w.image} alt={w.title} loading="lazy"/><h3>{w.title}</h3><p>{w.description}</p><span>View project ↗</span></a>)}</div></section>}
    <section className={`${s.container} ${s.section}`}><div className={s.sectionHeading}><div><span className={s.eyebrow}>AAPKE BUSINESS KE LIYE</span><h2>Ek team.<br/>Aapki online zaruratein.</h2></div><p>Alag-alag services ki list mein ulajhne ki zarurat nahi. Humein batayein aap kya karwana chahte hain.</p></div><div className={s.services}>{[["01", "Business ko online laayein", "Google, Facebook, Instagram aur WhatsApp Business profiles ki setup aur branding."], ["02", "Social media active rakhein", "Reels, photo posts, captions aur regular posting. Selected plans mein content shoots bhi."], ["03", "Professional website banwayein", "Aapke business, services aur contact details ke liye mobile-friendly website."], ["04", "Google presence sambhalein", "Business profile updates, weekly posts aur visibility improve karne ka ongoing kaam."]].map(([n, title, text]) => <article key={n} className={s.serviceCard}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={s.pricingSection}><div className={s.container}><span className={s.eyebrow}>PEHLE KHARCH KA ANDAAZA</span><h2>Shuruaat kitne se ho sakti hai?</h2><p className={s.sectionLead}>Har service alag hai. Yeh starting prices hain — final estimate aapki requirement ke baad milega.</p><div className={s.prices}>{[["Business profile setup", price("setup"), "one-time", "Naye business ke Google, Facebook, Instagram aur WhatsApp Business profiles ki setup."], ["Google profile management", price("gbp"), "per month", "Existing Google Business Profile ki updates, weekly posts aur optimization."], ["Business website", price("static"), "website price", "Up to 7 pages ki static, mobile-friendly business website."]].map(([title, amount, period, text]) => <article className={s.priceCard} key={title}><h3>{title}</h3><small>Starting from</small><p className={s.price}>{money(Number(amount))}<span>{period}</span></p><p>{text}</p><a href={contactHref()}>Details ke liye baat karein<Icon type="arrow"/></a></article>)}</div><p className={s.pricingNote}>Social media management ₹6,000/month se. Domain, hosting, taxes aur exact service terms quotation mein confirm honge.</p></div></section>
    <section className={`${s.container} ${s.section}`}><span className={s.eyebrow}>AISE SHURU HOGA KAAM</span><h2>Pehle samjhenge.<br/>Phir plan banayenge.</h2><div className={s.steps}>{[["01", "Aap humse baat karein", "Business aur jo help chahiye, woh batayein."], ["02", "Hum scope aur cost samjhayein", "Suitable package, included work aur charges clear karein."], ["03", "Aap agree karein, phir kaam shuru", "Client portal se service, orders aur project updates handle honge."]].map(([n, title, text]) => <div key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    {(content.testimonials.length > 0 || content.reviewsUrl) && <section className={`${s.container} ${s.section}`}><span className={s.eyebrow}>CLIENT FEEDBACK</span><h2>Hamare clients ki baat.</h2><div className={s.reviewGrid}>{content.testimonials.map(t => <figure key={t.name}><blockquote>“{t.quote}”</blockquote><figcaption><strong>{t.name}</strong><span>{t.business}</span></figcaption></figure>)}</div>{content.reviewsUrl && <a className={s.secondary} href={content.reviewsUrl} target="_blank" rel="noreferrer">Google par actual reviews dekhein ↗</a>}</section>}
    {offer && <section className={`${s.container} ${s.section}`}><div className={s.offer}><span className={s.eyebrow}>STARTER OFFER</span><h2>{offer.title}</h2>{active ? <><p>Regular price <del>{money(offer.regularPrice)}</del> · Offer price {money(offer.offerPrice)}</p><p className={s.offerPrice}>{money(offer.contactPrice)}<small>Deadline se pehle contact karne par</small></p><Countdown end={offer.endsAt}/><ul>{offer.inclusions.map(item => <li key={item}><Icon type="check"/>{item}</li>)}</ul><p>{offer.demoDescription}</p><ContactButtons offer/><p className={s.micro}>{offer.terms}</p></> : <><Countdown end={offer.endsAt}/><p>Current price aur available services ke liye humse baat karein.</p><ContactButtons/></>}</div></section>}
    <section className={`${s.container} ${s.section} ${s.faq}`}><span className={s.eyebrow}>BAAT KARNE SE PEHLE</span><h2>Aapke kuchh sawal.</h2>{[["Mujhe nahi pata kaunsa package chahiye.", "Koi baat nahi. Apna business aur requirement batayein. Hum suitable service, scope aur estimate samjhayenge."], ["Photos aur videos kaun dega?", "Basic, Growth aur Growth Plus mein raw photos/videos aap provide karenge. Professional aur higher social plans mein shoots included hain; location aur details pehle agree honge."], ["Ads ka paisa package mein included hai?", "Premium aur combined plans mein up to ₹2,000 ad budget included hai. Baaki plans mein ad banners listed hain; campaign management aur extra spend confirm karenge."], ["Kya leads ya ranking guarantee hoti hai?", "Hum kaam ka scope aur reporting clear karte hain. Leads, sales ya Google position ki guarantee nahi dete."]].map(([q, a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</section>
    <section className={`${s.container} ${s.section}`} id="contact"><div className={s.contact}><div><span className={s.eyebrow}>LET’S TALK ABOUT YOUR BUSINESS</span><h2>Aapki zarurat.<br/>Hamari next conversation.</h2><p>Abhi package decide karna zaroori nahi.<br/>Pehle samjhte hain aapke business ko kya chahiye.</p><ContactButtons/></div><div className={s.contactDetails}><img src={BRAND_LOGO.dark} width={BRAND_LOGO.width} height={BRAND_LOGO.height} alt={BRAND_LOGO.alt}/><a href={`mailto:${email}`}>{email}</a>{content.phone && <a href={`tel:${content.phone.replace(/[^+\d]/g, "")}`}>{content.phone}</a>}{content.address && <address>{content.address}</address>}{content.mapsUrl && <a href={content.mapsUrl} target="_blank" rel="noreferrer">Google Maps par dekhein ↗</a>}<p>Website · Social media · Google Business Profile</p></div></div></section>
    <footer className={`${s.container} ${s.footer}`}><span>© Mera Software · Digital Solutions</span><a href="/privacy">Privacy policy</a></footer><div className={s.sticky}><div><strong>Apne business ke liye baat karein</strong><span>Service aur estimate samajhiye.</span></div><a className={s.primary} href={contactHref()}><Icon type="message"/>{content.whatsapp ? "WhatsApp karein" : "Message karein"}</a>{content.phone && <a className={s.stickyCall} href={`tel:${content.phone.replace(/[^+\d]/g, "")}`} aria-label="Call Mera Software"><Icon type="phone"/></a>}</div>
  </main>;
}
